apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels: 
    app: webapp
spec:
  containers:
  - name: ubuntu
    image: ubuntu:trusty
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
    command: ["echo"]
    args: ["Hello-World"]
