apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels: 
    app: webapp
    release: "0"
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0
    command: ["echo"]
    args: ["Hello-World"]
    
    
# Satu file yaml, support untuk banyak Pod, berkikut contoh nya
---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-reliease0-5
  labels: 
    app: webapp
    release: "0-5"
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
    command: ["echo"]
    args: ["Hello-World"]
